# Generated by Django 4.0.2 on 2025-06-02 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Funcionário: ')),
                ('registration_id', models.CharField(max_length=255, unique=True, verbose_name='Matrícula')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Setor')),
                ('active', models.BooleanField(verbose_name='Funcionário Ativo')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da refeição')),
                ('meal_time', models.TimeField(auto_now_add=True, verbose_name='Hora da refeição')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
            },
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('employee', 'meal_date'), name='unique_meal_per_employee'),
        ),
    ]
